#!/usr/bin/env bash
set -e

USAGE="\

git sync [upstream name] [upstream branch] [commit hash]
"

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    echo "Not a git repository!" 1>&2
    exit 1
fi

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

UPSTREAM=$1
UPSTREAM_BRANCH=$2
UPSTREAM_COMMIT=$3

if [[ -z "$UPSTREAM_BRANCH" ]]; then
    UPSTREAM_BRANCH=$CURRENT_BRANCH
fi

if [[ -n "$UPSTREAM" ]]; then
    git checkout .
    git checkout "$CURRENT_BRANCH"
    git fetch "$UPSTREAM"
    git merge "$UPSTREAM"/"$UPSTREAM_BRANCH"
    if [[ -n "$UPSTREAM_COMMIT" ]]; then
        git reset --hard "$UPSTREAM_COMMIT"
        git push --force origin "$CURRENT_BRANCH"
    else
        git push origin "$CURRENT_BRANCH"
    fi
else
    echo "$USAGE"
fi
