#!/usr/bin/env bash

USAGE="\
git sync [upstream name]
"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

UPSTREAM=$1

if [ -n "$UPSTREAM" ]; then
    git checkout .
    git checkout "$CURRENT_BRANCH"
    git fetch "$UPSTREAM"
    git merge "$UPSTREAM"/"$CURRENT_BRANCH"
    git push origin "$CURRENT_BRANCH"
else
    echo $USAGE
fi
