#!/usr/bin/env bash

if [ -d ".git" ]; then
    AUTHOR=$(git config --local --get user.name)
    if [ -z "$AUTHOR" ]; then
        AUTHOR=$(git config --global --get user.name)
    fi
    if [ -n "$AUTHOR" ]; then
        echo $AUTHOR
        git log --author="$AUTHOR" --pretty=tformat: --numstat | awk '{ add += $1; subs += $2; loc += $1 + $2 } END { printf "新增代码行:\t%s\n删除代码行:\t%s\n总计代码行:\t%s\n", add, subs, loc }' -
    else
        echo "Can't get local git user!"
    fi
else
    echo "Not a git repository!"
fi
